-- MySQL Script generated by MySQL Workbench
-- Thu Jul 27 14:04:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema systemshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `systemshop` ;

-- -----------------------------------------------------
-- Schema systemshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `systemshop` DEFAULT CHARACTER SET utf8mb4 ;
USE `systemshop` ;

-- -----------------------------------------------------
-- Table `systemshop`.`dbo_estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemshop`.`dbo_estudiantes` (
  `Matricula` INT(11) NOT NULL,
  `Carrera` VARCHAR(50) NOT NULL,
  `Grupo` VARCHAR(5) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `ApPaterno` VARCHAR(50) NOT NULL,
  `ApMaterno` VARCHAR(50) NOT NULL,
  `Correo` VARCHAR(50) NOT NULL,
  `Contra` VARCHAR(50) NOT NULL,
  `Activo` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `systemshop`.`dbo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemshop`.`dbo_producto` (
  `Id_Producto` INT(11) NOT NULL,
  `NombreProducto` VARCHAR(80) NOT NULL,
  `Detalles` VARCHAR(500) NOT NULL,
  `Precio` BIGINT(20) NOT NULL,
  `Marca` VARCHAR(50) NOT NULL,
  `Imagen` VARCHAR(100) NULL DEFAULT 'C:xampp2htdocsSYSTEMSHOPimgProductosDefault_ISC.png',
  `Estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `systemshop`.`dbo_estudiantes_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemshop`.`dbo_estudiantes_producto` (
  `Matricula` INT(11) NOT NULL,
  `Id_Producto` INT(11) NOT NULL,
  PRIMARY KEY (`Matricula`, `Id_Producto`),
  CONSTRAINT `FK_Estudiantes_Producto_Estudiantes`
    FOREIGN KEY (`Matricula`)
    REFERENCES `systemshop`.`dbo_estudiantes` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Estudiantes_Producto_Producto`
    FOREIGN KEY (`Id_Producto`)
    REFERENCES `systemshop`.`dbo_producto` (`Id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `FK_Estudiantes_Producto_Producto` ON `systemshop`.`dbo_estudiantes_producto` (`Id_Producto` ASC);


-- -----------------------------------------------------
-- Table `systemshop`.`dbo_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemshop`.`dbo_servicios` (
  `Id_servicios` INT(11) NOT NULL,
  `NombreServicio` VARCHAR(80) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(500) NOT NULL,
  `Fecha_inicio` DATE NOT NULL,
  `Fecha_Final` DATE NOT NULL,
  `Imagen` VARCHAR(100) NULL DEFAULT 'C:xampp2htdocsSYSTEMSHOPimgServiciosDefault_ISC.png',
  `Estado` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_servicios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `systemshop`.`dbo_estudiantes_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemshop`.`dbo_estudiantes_servicios` (
  `Matricula` INT(11) NOT NULL,
  `Id_Servicios` INT(11) NOT NULL,
  PRIMARY KEY (`Matricula`, `Id_Servicios`),
  CONSTRAINT `FK_Estudiantes_Servicios_Estudiantes`
    FOREIGN KEY (`Matricula`)
    REFERENCES `systemshop`.`dbo_estudiantes` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Estudiantes_Servicios_Servicios`
    FOREIGN KEY (`Id_Servicios`)
    REFERENCES `systemshop`.`dbo_servicios` (`Id_servicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `FK_Estudiantes_Servicios_Servicios` ON `systemshop`.`dbo_estudiantes_servicios` (`Id_Servicios` ASC);

USE `systemshop` ;

-- -----------------------------------------------------
-- procedure ObtenerProductosPorEstudiante
-- -----------------------------------------------------

DELIMITER $$
USE `systemshop`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ObtenerProductosPorEstudiante`(IN Matricula VARCHAR(50))
BEGIN
    SELECT p.* FROM dbo_producto p
    INNER JOIN dbo_estudiantes_producto ep ON p.id_Producto = ep.id_Producto
    WHERE ep.Matricula = Matricula;
END$$

DELIMITER ;
USE `systemshop`;

DELIMITER $$
USE `systemshop`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `systemshop`.`tr_ActualizarEstudianteActivo`
AFTER INSERT ON `systemshop`.`dbo_estudiantes`
FOR EACH ROW
BEGIN
    UPDATE dbo_estudiantes
    SET Activo = 'SI'
    WHERE Matricula = NEW.Matricula;
END$$

USE `systemshop`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `systemshop`.`tr_Establecer_Estatus_Servicio`
AFTER INSERT ON `systemshop`.`dbo_servicios`
FOR EACH ROW
BEGIN
    IF NEW.Fecha_Final > NOW() THEN
        UPDATE dbo_servicios
        SET Estado = 'DISPONIBLE'
        WHERE Id_servicios = NEW.Id_servicios;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
